version: '3.9'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: tamkeen
      POSTGRES_USER: tamkeen
      POSTGRES_PASSWORD: tamkeen
    ports:
      - '5432:5432'

  redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - '2181:2181'

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'

  api-gateway:
    build: ./services/api-gateway
    environment:
      JWT_SECRET: secret
      KAFKA_BROKERS: kafka:9092
    ports:
      - '8080:8080'
    depends_on:
      - kafka
      - postgres
      - redis

  auth-service:
    build: ./services/auth-service
    environment:
      DATABASE_URL: postgresql://tamkeen:tamkeen@postgres:5432/tamkeen
      JWT_SECRET: secret
      JWT_REFRESH_SECRET: refresh
    depends_on:
      - postgres
    ports:
      - '3001:3001'

  transaction-service:
    build: ./services/transaction-service
    environment:
      DATABASE_URL: postgresql://tamkeen:tamkeen@postgres:5432/tamkeen
      REDIS_URL: redis://redis:6379
      KAFKA_BROKERS: kafka:9092
    depends_on:
      - postgres
      - redis
      - kafka
    ports:
      - '3002:3002'
